[package]
name = "hw"
version = "0.1.0"
edition = "2021"

[dependencies]
maud = "0.26.0"
actix-web = "4.8.0"
actix-files = "0.6.2"
actix-multipart = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"